services:
  - type: web
    name: vidushi
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    staticPublishPath: videos  # વિડિઓ ફાઇલો માટે
